#!/bin/bash
# Deploys this repo to production (webserver -> https://web.abofonsa.com) and verifies the result.
# Run it by hand from a clean checkout of the commit you want live:
#
#   ./deploy.sh                 # build+push images, ship config, restart, verify
#   ./deploy.sh --skip-build    # redeploy an already-pushed TAG (e.g. a rollback)
#   ./deploy.sh --verify-only   # touch nothing, just run the health/HTTP checks
#   TAG=a1b2c3d ./deploy.sh --skip-build   # roll back to a previous image
#   ./deploy.sh --yes           # non-interactive; skips the prompts (NOT the certbot one)
#
#   ./deploy.sh --recover       # stack is running but its compose.yml/.env went missing
#   ./deploy.sh --bootstrap     # FIRST-TIME INSTALL on a server with nothing deployed
#   ./deploy.sh --bootstrap --with-nginx        # ... and install the host nginx site
#   ./deploy.sh --bootstrap --with-nginx --with-tls   # ... and run certbot for the domain
#
# CHANNELS - where the images being deployed come from:
#
#   ./deploy.sh --channel local    # (default) build them here, push to the private registry
#   ./deploy.sh --channel github   # deploy the images GitHub Actions already built, from GHCR
#
#   local   builds both images on this machine with ./build.sh and pushes them to
#           docker.jojoaddison.net. What you deploy is what your working tree produces.
#   github  builds nothing. .github/workflows/release.yml built and pushed the images to
#           ghcr.io/$GHCR_OWNER when the commit landed on main; this deploys exactly those.
#           The tag is the FULL commit SHA, because that is what the workflow tags with.
#
#           TAG=<full-sha> ./deploy.sh --channel github   # deploy/roll back to any built commit
#
# The channel decides two things and nothing else: whether a build runs here, and what REGISTRY
# the server's .env is pointed at. Everything after that - config sync, restart, health, the
# verification suite - is identical, so a deploy cannot behave differently depending on where its
# image was built.
#
# What it does, in order: preflight -> [bootstrap: create dirs/networks/.env, ship config] ->
# build+push (local channel) or confirm the image is pullable (github channel) -> sync compose.yml
# -> point the server's .env at the new REGISTRY+TAG -> pull + recreate -> wait for the API to
# report healthy -> [bootstrap: nginx + TLS] -> verify internally and publicly. Every mutating step
# is announced before it runs, and the irreversible-ish ones prompt unless --yes is passed.
#
# All three secrets this app needs (JWT_SIGNING_KEY, BOOTSTRAP_ADMIN_PASSWORD, ENQUIRY_IP_SALT) are
# generated by `openssl rand` running ON THE SERVER during bootstrap, so they never exist on the
# deploying machine, in its shell history, or on the wire. Unlike the sibling app there is no
# third-party key to supply by hand, so nothing has to be pasted in.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

# --- Configuration -----------------------------------------------------------------------------

SSH_HOST="${SSH_HOST:-webserver}"                                # ~/.ssh/config alias
REMOTE_DIR="${REMOTE_DIR:-~/webroot/01-healthconnect/abofonsa}"  # expanded remotely, not here
PUBLIC_URL="${PUBLIC_URL:-https://web.abofonsa.com}"
FRONTEND_PORT="${FRONTEND_PORT:-8082}"   # loopback-only port the host nginx proxies to
# Must match `container_name:` in infra/prod-server/compose.yml. Hyphens, not underscores: an
# underscore is illegal in a hostname, so a container named hc_abofonsa_api cannot be addressed
# over the compose network without Tomcat rejecting the request with a bare 400.
API_CONTAINER="abofonsa-api"
WEB_CONTAINER="abofonsa-web"
MONGO_CONTAINER="abofonsa-mongodb"
APP_NETWORK="abofonsanet"
NGINX_CONF="abofonsa.conf"

# The OTel javaagent baked into the API image costs real boot time on this single-core host.
# This is expected, not a hang - see infra/prod-server/compose.yml's healthcheck comment.
HEALTH_TIMEOUT_SECS="${HEALTH_TIMEOUT_SECS:-720}"
HEALTH_POLL_SECS=10

# Image source. REGISTRY is normally derived from the channel below, but an explicit REGISTRY in
# the environment still wins for either channel - captured here, before the channel overwrites it.
LOCAL_REGISTRY="docker.jojoaddison.net"
GHCR_OWNER="${GHCR_OWNER:-kojoampia}"      # ghcr.io/<owner>, matches release.yml's repository_owner
REGISTRY_OVERRIDE="${REGISTRY:-}"

# --- Argument parsing --------------------------------------------------------------------------

CHANNEL="local"
SKIP_BUILD=false
VERIFY_ONLY=false
ASSUME_YES=false
BOOTSTRAP=false
RECOVER=false
WITH_NGINX=false
WITH_TLS=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    # Guarded: a bare trailing `--channel` would otherwise shift twice off a one-element list and
    # abort on the failed shift, swallowing the "needs a value" message below.
    --channel)     CHANNEL="${2:-}"; if [[ $# -gt 1 ]]; then shift; fi ;;
    --channel=*)   CHANNEL="${1#--channel=}" ;;
    --skip-build)  SKIP_BUILD=true ;;
    --verify-only) VERIFY_ONLY=true; SKIP_BUILD=true ;;
    --yes|-y)      ASSUME_YES=true ;;
    --bootstrap)   BOOTSTRAP=true ;;
    --recover)     RECOVER=true; SKIP_BUILD=true ;;
    --with-nginx)  WITH_NGINX=true ;;
    --with-tls)    WITH_TLS=true; WITH_NGINX=true ;;
    -h|--help)     sed -n '2,38p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

case "$CHANNEL" in
  local)  REGISTRY="${REGISTRY_OVERRIDE:-$LOCAL_REGISTRY}" ;;
  github)
    REGISTRY="${REGISTRY_OVERRIDE:-ghcr.io/$GHCR_OWNER}"
    # The images already exist; there is nothing here to build and a local build would produce a
    # different image under the same name. Forced rather than merely defaulted, so
    # `--channel github` cannot be combined into something that quietly rebuilds.
    SKIP_BUILD=true
    ;;
  "") echo "--channel needs a value: local or github" >&2; exit 2 ;;
  *)  echo "unknown channel '$CHANNEL' (expected: local, github)" >&2; exit 2 ;;
esac

# Domain for the nginx site and certbot, derived from PUBLIC_URL (https://host -> host).
# Only this one host is served: the apex (abofonsa.com) is deliberately not claimed, because it is
# a separate hostname that may already serve something else. See infra/prod-server/nginx-abofonsa.conf.
PUBLIC_HOST="${PUBLIC_URL#https://}"; PUBLIC_HOST="${PUBLIC_HOST#http://}"; PUBLIC_HOST="${PUBLIC_HOST%%/*}"

# Channel-dependent, and it has to be: build.sh tags with the short SHA, while release.yml tags
# with ${{ github.sha }} - the full 40-character one. Defaulting to the short SHA on the github
# channel would look up an image that was never pushed and fail with a bare manifest-unknown.
if [[ -z "${TAG:-}" ]]; then
  if [[ "$CHANNEL" == "github" ]]; then TAG="$(git rev-parse HEAD)"; else TAG="$(git rev-parse --short HEAD)"; fi
fi

# --- Output helpers ----------------------------------------------------------------------------

if [[ -t 1 ]]; then
  BOLD=$'\033[1m'; RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RESET=$'\033[0m'
else
  BOLD=""; RED=""; GREEN=""; YELLOW=""; RESET=""
fi

step()  { echo ""; echo "${BOLD}==> $*${RESET}"; }
ok()    { echo "  ${GREEN}✓${RESET} $*"; }
warn()  { echo "  ${YELLOW}!${RESET} $*"; }
fail()  { echo "  ${RED}✗${RESET} $*"; }
die()   { echo ""; echo "${RED}${BOLD}Aborted:${RESET} $*" >&2; exit 1; }

confirm() {
  $ASSUME_YES && return 0
  local reply
  read -r -p "  ${BOLD}$1${RESET} [y/N] " reply
  [[ "$reply" =~ ^[Yy]$ ]] || die "declined at: $1"
}

# -n matters: without it ssh reads this script's stdin and forwards it to the remote command,
# which silently eats the answers to the confirm() prompts below. The one place that genuinely
# needs stdin - writing .env during bootstrap - calls ssh directly.
remote() { ssh -n "$SSH_HOST" "$@"; }
in_dir() { ssh -n "$SSH_HOST" "cd $REMOTE_DIR && $*"; }

# Tracks non-fatal problems so the final summary reports them together rather than burying them.
WARNINGS=()
note_warning() { WARNINGS+=("$1"); warn "$1"; }

# Rewrites a key in the server's .env, appending it if it is absent. sed alone is not enough: a
# `sed -i 's/^REGISTRY=.*/.../'` against an .env that predates the github channel matches nothing
# and exits 0, leaving compose.yml to fall back to its built-in `${REGISTRY:-docker.jojoaddison.net}`
# and pull the old registry's copy of a tag that only exists on GHCR.
# `|` is the sed delimiter because every registry value contains slashes.
set_env_key() {
  local key="$1" value="$2"
  in_dir "if grep -q '^$key=' .env; then sed -i 's|^$key=.*|$key=$value|' .env; \
          else printf '%s\n' '$key=$value' >> .env; fi"
}

# Rolling back means restoring the previous IMAGE, and the previous image may have come from the
# other channel - so the hint has to name the channel that can actually produce it. Suggesting
# `--skip-build` for a GHCR deployment would reset REGISTRY to the private registry and look for a
# full-SHA tag that was never pushed there. Reads the globals when called, after they are known.
rollback_hint() {
  case "${PREVIOUS_REGISTRY:-}" in
    ghcr.io/*) echo "TAG=${PREVIOUS_TAG:-<previous>} ./deploy.sh --channel github" ;;
    *)         echo "TAG=${PREVIOUS_TAG:-<previous>} ./deploy.sh --skip-build" ;;
  esac
}

# --- 1. Preflight ------------------------------------------------------------------------------

step "Preflight"

echo "  target:   $SSH_HOST:$REMOTE_DIR"
echo "  public:   $PUBLIC_URL"
echo "  channel:  $CHANNEL$([[ "$CHANNEL" == github ]] && echo '  (images built by GitHub Actions)' || echo '  (images built here by ./build.sh)')"
echo "  registry: $REGISTRY${REGISTRY_OVERRIDE:+  (from \$REGISTRY, overriding the channel default)}"
echo "  tag:      $TAG"
if $VERIFY_ONLY; then                    MODE_DESC="verify only"
elif [[ "$CHANNEL" == "github" ]]; then  MODE_DESC="deploy the GitHub-built image (nothing is built here)"
elif $SKIP_BUILD; then                   MODE_DESC="redeploy (no build)"
else                                     MODE_DESC="full build + deploy"
fi
echo "  mode:     $MODE_DESC"

command -v docker >/dev/null || die "docker not found on PATH"
command -v ssh    >/dev/null || die "ssh not found on PATH"

ssh -n -o BatchMode=yes -o ConnectTimeout=10 "$SSH_HOST" true 2>/dev/null \
  || die "cannot ssh to '$SSH_HOST' non-interactively. Check ~/.ssh/config and your agent."
ok "ssh to $SSH_HOST works"

# The container names above are duplicated from compose.yml, and drifted once already: compose was
# renamed and this script kept polling a container that no longer existed, so a perfectly good
# deploy sat waiting for health on a ghost. Check the two agree before doing anything.
for expected in "$API_CONTAINER" "$WEB_CONTAINER" "$MONGO_CONTAINER"; do
  grep -q "container_name: *$expected\b" infra/prod-server/compose.yml \
    || die "this script expects a container named '$expected', but infra/prod-server/compose.yml
        does not declare it. The two have drifted - reconcile them before deploying."
done
ok "container names agree with compose.yml"

CONTAINERS_EXIST=false
remote "docker inspect $API_CONTAINER >/dev/null 2>&1" && CONTAINERS_EXIST=true

if remote "test -f $REMOTE_DIR/compose.yml && test -f $REMOTE_DIR/.env"; then
  ok "remote deployment directory looks initialized"
  if $BOOTSTRAP; then
    # Re-running --bootstrap over a live install regenerates .env with new secrets. That orphans
    # nothing in Mongo (it has no password here), but it DOES invalidate every issued admin token
    # and silently reset every enquiry rate-limit bucket - a confusing state that looks like a
    # broken build. Refuse instead.
    die "$REMOTE_DIR already has compose.yml and .env - this is an existing install, not a new one.
        Drop --bootstrap to deploy to it normally. If you really want to start over, remove
        $REMOTE_DIR (and its Docker volumes) on the server first, deliberately."
  fi
elif $CONTAINERS_EXIST && $RECOVER; then
  warn "config files are missing but the stack is running - recovering them"
elif $CONTAINERS_EXIST; then
  # The dangerous case, and the reason --recover exists: the stack is running but its compose.yml
  # and .env are gone. Bootstrapping over this looks like the obvious move and is destructive:
  #
  #   - It generates a new BOOTSTRAP_ADMIN_PASSWORD, but the admin user was already seeded and the
  #     changelog runner records V008 as applied, so it will NOT be re-seeded. The new password
  #     matches nothing, and the old one is gone with the .env - CMS access is lost permanently.
  #   - It generates a new JWT_SIGNING_KEY and ENQUIRY_IP_SALT, invalidating every session and
  #     silently resetting every rate-limit bucket.
  #
  # The secrets are still recoverable, because the running containers hold them in their
  # environment. --recover reconstructs .env from there instead of inventing new values.
  die "$REMOTE_DIR has no compose.yml/.env, but $API_CONTAINER is running.

        The stack is orphaned: it is serving, but nothing on the server can manage it - no
        compose file to act on, and the secrets exist only inside the running containers.

        Do NOT bootstrap over this. Bootstrapping would generate a new BOOTSTRAP_ADMIN_PASSWORD
        that cannot match the already-seeded admin user (the migration will not re-run), and the
        real one would be gone for good.

        Run:  ./deploy.sh --recover
        which rebuilds .env from the running containers' own environment and ships the missing
        files back, changing no secret and restarting nothing."
elif $RECOVER; then
  die "--recover expects a running stack whose config files are missing, but $API_CONTAINER
        does not exist. There is nothing to recover secrets from; use --bootstrap for a fresh
        install."
else
  $BOOTSTRAP || die "$REMOTE_DIR is missing compose.yml and/or .env, so there is nothing to update.
        For a first-time install, re-run with --bootstrap (add --with-nginx --with-tls to also
        set up the host nginx site and its certificate). See
        infra/PRODUCTION_DEPLOYMENT_PLAN.md for what that provisions."
  warn "no existing deployment found - will bootstrap a new one"
fi

if ! $SKIP_BUILD; then
  # Deploying a dirty tree means the pushed image doesn't match any commit, which makes the TAG
  # meaningless for tracing a bug back to source later.
  if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then
    note_warning "working tree has uncommitted changes - image $TAG will not match commit $TAG"
    confirm "Build and push anyway?"
  else
    ok "working tree clean (image tag $TAG matches the commit)"
  fi
elif [[ "$CHANNEL" == "github" ]] && ! $VERIFY_ONLY && ! $RECOVER; then
  # A dirty tree means something different on this channel, and something quieter. Nothing is built
  # here, so there is no mismatched tag to warn about - the image for $TAG was built from the commit
  # and simply does not contain the changes sitting in front of you. Without this you can edit,
  # deploy, and watch the edit not appear, with every step reporting success.
  if [[ "$TAG" == "$(git rev-parse HEAD)" && -n "$(git status --porcelain --untracked-files=no)" ]]; then
    note_warning "working tree has uncommitted changes, and this channel deploys the image built from commit $TAG - your local edits are NOT in it"
  fi
fi

PREVIOUS_TAG=""
PREVIOUS_REGISTRY=""
if ! $BOOTSTRAP; then
  PREVIOUS_TAG="$(in_dir "grep -E '^TAG=' .env | cut -d= -f2" || true)"
  PREVIOUS_REGISTRY="$(in_dir "grep -E '^REGISTRY=' .env | cut -d= -f2" || true)"
  [[ -n "$PREVIOUS_TAG" ]] && echo "  currently deployed tag: ${BOLD}${PREVIOUS_TAG}${RESET}"
  # Switching channels is legitimate and is exactly what this flag is for, but it is also the kind
  # of thing worth seeing stated rather than inferring from a pull that suddenly takes five minutes.
  if [[ -n "$PREVIOUS_REGISTRY" && "$PREVIOUS_REGISTRY" != "$REGISTRY" ]] && ! $VERIFY_ONLY && ! $RECOVER; then
    echo "  ${BOLD}registry change:${RESET} $PREVIOUS_REGISTRY -> $REGISTRY"
  fi
fi

# --verify-only inspects whatever is already live, so the local checkout's commit is irrelevant -
# without this the image-tag check below would "fail" simply because you have newer local commits.
# The registry follows for the same reason: what is live may well have come from the other channel.
if $VERIFY_ONLY && [[ -n "$PREVIOUS_TAG" ]]; then
  TAG="$PREVIOUS_TAG"
  REGISTRY="${PREVIOUS_REGISTRY:-$REGISTRY}"
fi

# --- 1a. github channel: prove the images exist before touching anything -----------------------
# Deliberately the last thing in preflight, and deliberately not in the build step further down:
# every message below promises the server is untouched, and that promise has to still be true when
# it prints. Bootstrap creates directories, a network and an .env before the build step is reached,
# so a probe placed there could only apologise for work already done.

if [[ "$CHANNEL" == "github" ]] && ! $VERIFY_ONLY && ! $RECOVER; then
  step "Checking the GitHub-built images for $TAG are pullable from $SSH_HOST"
  echo "  Nothing is built on this channel. .github/workflows/release.yml built and pushed these"
  echo "  when the commit landed on main; this only confirms they are there and reachable."
  echo ""
  echo "  The probe runs ON THE SERVER, not here, because the server is what pulls: a local"
  echo "  ~/.docker/config.json that happens to hold a GHCR token proves nothing about whether"
  echo "  the deploy will work. Checking it here would turn a permissions problem into a failed"
  echo "  'docker compose pull' after .env has already been rewritten to a tag that cannot start."

  GHCR_MISSING=()
  GHCR_UNAUTHORIZED=false
  GHCR_PROBE_UNSUPPORTED=false
  for image in "$REGISTRY/abofonsa-api:$TAG" "$REGISTRY/abofonsa-web:$TAG"; do
    # stderr only: the manifest JSON itself is noise, the error text is the diagnosis.
    if probe_err="$(remote "docker manifest inspect '$image' 2>&1 >/dev/null")"; then
      ok "$image"
    else
      # GHCR answers an unauthenticated request for a private package with 'denied'/'unauthorized'
      # rather than 404 - deliberately, so the registry does not leak which packages exist. The two
      # cases need completely different fixes, so they are told apart rather than merged into
      # "could not find the image".
      case "$probe_err" in
        *nauthorized*|*denied*|*"requested access"*) GHCR_UNAUTHORIZED=true ;;
        # `docker manifest` needed DOCKER_CLI_EXPERIMENTAL=enabled before CLI 20.10. That says
        # nothing about the image, and blocking a perfectly good deploy on it - while reporting it
        # as a missing tag - would be worse than not checking at all.
        *xperimental*) GHCR_PROBE_UNSUPPORTED=true ;;
      esac
      GHCR_MISSING+=("$image")
      fail "$image -> ${probe_err:-not reachable}"
    fi
  done

  if $GHCR_PROBE_UNSUPPORTED; then
    note_warning "$SSH_HOST's docker CLI does not support 'docker manifest inspect' - could not pre-check the images"
    echo "      The deploy continues unchecked; if the images are absent or the credential is"
    echo "      missing, it will fail at 'docker compose pull' in a few steps' time instead."
    GHCR_MISSING=()
  fi

  if (( ${#GHCR_MISSING[@]} > 0 )); then
    if $GHCR_UNAUTHORIZED; then
      if remote "grep -q ghcr.io ~/.docker/config.json 2>/dev/null"; then
        die "$SSH_HOST has a stored ghcr.io credential but GHCR still refused the pull.

        The token is most likely expired, or lacks the read:packages scope. Refresh it on the
        server with a token that has read:packages:

          ssh $SSH_HOST 'echo <TOKEN> | docker login ghcr.io -u $GHCR_OWNER --password-stdin'

        Nothing has been changed on the server; the running deployment is untouched."
      fi
      die "these packages are private and $SSH_HOST has no ghcr.io credential.

        Either make the packages public (GitHub -> Packages -> abofonsa-api / abofonsa-web ->
        Package settings -> Change visibility), which needs no credential on the server at all,
        or store a read-only token there once:

          ssh $SSH_HOST 'echo <TOKEN> | docker login ghcr.io -u $GHCR_OWNER --password-stdin'

        The token needs the read:packages scope and nothing else - it is only ever used to pull.
        Nothing has been changed on the server; the running deployment is untouched."
    fi
    # owner/repo out of the git remote, handling both the SSH and HTTPS forms, so the link is
    # clickable rather than a placeholder - and stays right if the repo moves or is forked.
    REPO_SLUG="$(git remote get-url origin 2>/dev/null || true)"
    REPO_SLUG="${REPO_SLUG%.git}"
    REPO_SLUG="${REPO_SLUG#*github.com}"
    REPO_SLUG="${REPO_SLUG#[:/]}"
    case "$REPO_SLUG" in
      */*) ACTIONS_URL="https://github.com/$REPO_SLUG/actions/workflows/release.yml" ;;
      *)   ACTIONS_URL="https://github.com/$GHCR_OWNER/<repo>/actions/workflows/release.yml" ;;
    esac
    die "GHCR has no image tagged $TAG.

        This channel deploys what GitHub Actions built, so a missing tag means the Release
        workflow has not produced this commit: it may not be merged to main yet, or the run
        failed, or you are deploying a commit that only exists locally.

          - check the run:  $ACTIONS_URL
          - to deploy a different, already-built commit:  TAG=<full-sha> ./deploy.sh --channel github
          - to deploy this working tree instead:          ./deploy.sh   (the local channel)

        Note the tag is the FULL 40-character SHA on this channel, not the short one build.sh uses.

        Nothing has been changed on the server; the running deployment is untouched."
  fi
  # Not printed when the probe could not run: an unchecked deploy must not report a clean check.
  $GHCR_PROBE_UNSUPPORTED || ok "both images exist on GHCR and $SSH_HOST can pull them"
fi

# --- 1b. Recover an orphaned deployment --------------------------------------------------------
# Puts the missing files back without touching the running containers. The secrets come out of the
# API container's own environment, so they stay identical to what the database was seeded with -
# which is the whole point, since a regenerated BOOTSTRAP_ADMIN_PASSWORD would match nothing.

if $RECOVER; then
  step "Recovering $REMOTE_DIR from the running stack"
  echo "  Rebuilds compose.yml, start, infra.sh, backup.sh and .env."
  echo "  Secrets are read from $API_CONTAINER's environment on the server and never leave it."
  echo "  Nothing is restarted and no secret changes."
  confirm "Proceed with recovery?"

  remote "mkdir -p $REMOTE_DIR/backups"
  scp -q infra/prod-server/compose.yml infra/prod-server/start \
         infra/prod-server/infra.sh infra/prod-server/backup.sh "$SSH_HOST:$REMOTE_DIR/"
  remote "chmod +x $REMOTE_DIR/start $REMOTE_DIR/infra.sh $REMOTE_DIR/backup.sh"
  ok "restored compose.yml, start, infra.sh, backup.sh"

  # Entirely server-side: docker inspect feeds the values straight into .env, so no secret is
  # printed here or crosses the wire. The running image reference is recovered the same way, so the
  # rebuilt .env pins exactly what is live rather than guessing `latest` - or guessing a registry.
  # REGISTRY below is only a fallback for the impossible case where the image reference has no
  # registry component; the live reference is what decides, because with two channels the flag this
  # invocation happened to be given is no longer evidence of where the running images came from.
  # shellcheck disable=SC2087  # the inner heredoc must expand remotely
  ssh "$SSH_HOST" \
    "ENV_PATH=$REMOTE_DIR/.env API_CONTAINER='$API_CONTAINER' WEB_CONTAINER='$WEB_CONTAINER' \
     REGISTRY='$REGISTRY' FRONTEND_PORT='$FRONTEND_PORT' STAMP='$(date -u +%Y-%m-%dT%H:%M:%SZ)' \
     bash -s" <<'REMOTE_SCRIPT'
set -euo pipefail
umask 077

envof() { docker inspect "$1" --format '{{range .Config.Env}}{{println .}}{{end}}' | grep "^$2=" | cut -d= -f2-; }

JWT="$(envof "$API_CONTAINER" JWT_SIGNING_KEY)"
BOOTSTRAP_PW="$(envof "$API_CONTAINER" BOOTSTRAP_ADMIN_PASSWORD)"
SALT="$(envof "$API_CONTAINER" ENQUIRY_IP_SALT)"
ALLOWED="$(envof "$WEB_CONTAINER" ALLOWED_HOSTS)"
INDEXABLE="$(envof "$WEB_CONTAINER" SITE_INDEXABLE)"
# Split from the whole reference (registry/namespace/name:tag) rather than assumed, so a stack
# running GHCR images is recovered as a GHCR deployment and the next `docker compose pull` looks
# where the images actually are.
LIVE_IMAGE="$(docker inspect "$API_CONTAINER" --format '{{.Config.Image}}')"
LIVE_TAG="${LIVE_IMAGE##*:}"
case "$LIVE_IMAGE" in
  # Everything before the last slash: 'ghcr.io/owner' or 'docker.example.net' alike.
  */*) LIVE_REGISTRY="${LIVE_IMAGE%/*}" ;;
  # No slash means no registry component to recover; fall back to the invoking channel's value.
  # Testing the registry rather than the whole reference here would misread a bare 'abofonsa-api:tag'
  # as the registry 'abofonsa-api:tag' and write that into .env.
  *)   LIVE_REGISTRY="$REGISTRY" ;;
esac

for pair in "JWT_SIGNING_KEY:$JWT" "BOOTSTRAP_ADMIN_PASSWORD:$BOOTSTRAP_PW" "ENQUIRY_IP_SALT:$SALT"; do
  [ -n "${pair#*:}" ] || { echo "could not recover ${pair%%:*} from the container" >&2; exit 1; }
done

cat > "$ENV_PATH" <<ENVEOF
# Rebuilt by deploy.sh --recover on $STAMP from the running containers' environment.
# Every secret below is the value the live stack is already using - not a regenerated one.
REGISTRY=$LIVE_REGISTRY
TAG=$LIVE_TAG
FRONTEND_PORT=$FRONTEND_PORT

JWT_SIGNING_KEY=$JWT
BOOTSTRAP_ADMIN_PASSWORD=$BOOTSTRAP_PW
ENQUIRY_IP_SALT=$SALT

ALLOWED_HOSTS=${ALLOWED:-web.abofonsa.com}
SITE_INDEXABLE=${INDEXABLE:-false}
ENVEOF
chmod 600 "$ENV_PATH"
echo "recovered REGISTRY=$LIVE_REGISTRY TAG=$LIVE_TAG"
REMOTE_SCRIPT
  ok "rebuilt .env (mode 600) from the live containers - no secret changed"

  in_dir "docker compose --env-file .env -f compose.yml config >/dev/null" \
    && ok "compose.yml + .env resolve cleanly" \
    || die "the recovered files do not resolve - inspect $REMOTE_DIR/.env by hand"

  # JWT_SIGNING_KEY and ENQUIRY_IP_SALT are recovered soundly, because the live container is
  # *using* them right now - its copy is the truth by definition.
  #
  # BOOTSTRAP_ADMIN_PASSWORD is different in kind, and assuming otherwise is a trap this script
  # walked into once. It matters only at seed time: V008 hashes it into the admin record on first
  # boot and is then recorded in `schemaMigrations`, never to run again. A container started later
  # can therefore carry a perfectly valid-looking value that has nothing to do with the stored
  # hash - which is exactly what happens when a failed deploy recreates the stack with a freshly
  # generated .env. Recovering that value silently would hand over a password that cannot work.
  #
  # So it is tested, on the server, against the running API. Addressed by the compose service
  # alias rather than the container name: `hc_abofonsa_api` contains underscores, which are illegal
  # in a hostname, and Tomcat rejects the request with a bare 400 before Spring ever sees it.
  step "Checking the recovered admin password actually works"
  RECOVERED_LOGIN_CODE="$(remote "cd $REMOTE_DIR && python3 -c \"
import json,re,pathlib
env=dict(re.match(r'^([A-Z_]+)=(.*)\$', l).groups() for l in pathlib.Path('.env').read_text().splitlines() if re.match(r'^[A-Z_]+=', l))
pathlib.Path('/tmp/.abofonsa-login-probe.json').write_text(json.dumps({'username':'admin','password':env['BOOTSTRAP_ADMIN_PASSWORD']}))
\" && docker run --rm --network $APP_NETWORK -v /tmp/.abofonsa-login-probe.json:/p.json:ro curlimages/curl:latest \
       -s -o /dev/null -w '%{http_code}' -X POST http://api:8080/api/v1/admin/auth/login \
       -H 'Content-Type: application/json' --data-binary @/p.json; rm -f /tmp/.abofonsa-login-probe.json" || echo "000")"

  case "$RECOVERED_LOGIN_CODE" in
    200) ok "BOOTSTRAP_ADMIN_PASSWORD authenticates - CMS access is intact" ;;
    401)
      note_warning "the recovered BOOTSTRAP_ADMIN_PASSWORD does NOT authenticate"
      echo "      This value is not the one the admin account was seeded with, so nobody can sign"
      echo "      in to the CMS. It is not recoverable: only its BCrypt hash was ever stored, and"
      echo "      V008_seed_admin_user is already recorded in schemaMigrations, so it will not"
      echo "      re-run on its own."
      echo ""
      echo "      To reset the account to the password now in .env - this DELETES the unusable"
      echo "      admin user and lets the seeder recreate it, so run it deliberately:"
      echo ""
      echo "        ssh $SSH_HOST \"docker exec $MONGO_CONTAINER mongosh abofonsa --quiet --eval '"
      echo "          db.adminUsers.deleteMany({username: \\\"admin\\\"});"
      echo "          db.schemaMigrations.deleteOne({_id: \\\"V008_seed_admin_user\\\"});'\""
      echo "        ssh $SSH_HOST 'cd $REMOTE_DIR && docker compose --env-file .env -f compose.yml restart api'"
      echo ""
      echo "      The recreated account keeps mustChangePassword=true, so the first login must"
      echo "      still rotate it. Any other admin users are untouched."
      ;;
    *) note_warning "could not verify BOOTSTRAP_ADMIN_PASSWORD (login probe returned $RECOVERED_LOGIN_CODE)" ;;
  esac

  PREVIOUS_TAG="$(in_dir "grep -E '^TAG=' .env | cut -d= -f2" || true)"
  PREVIOUS_REGISTRY="$(in_dir "grep -E '^REGISTRY=' .env | cut -d= -f2" || true)"
  echo "  recovered image: ${BOLD}${PREVIOUS_REGISTRY}/abofonsa-api:${PREVIOUS_TAG}${RESET}"
  TAG="$PREVIOUS_TAG"
  REGISTRY="${PREVIOUS_REGISTRY:-$REGISTRY}"
fi

# --- 1c. Bootstrap: provision a brand-new deployment -------------------------------------------
# The code form of infra/PRODUCTION_DEPLOYMENT_PLAN.md steps 1-3. nginx and TLS (steps 4) come
# later, after the stack is proven healthy on the server itself.

if $BOOTSTRAP; then
  step "Bootstrapping a new deployment at $SSH_HOST:$REMOTE_DIR"
  echo "  This will create:"
  echo "    - $REMOTE_DIR/ (plus backups/)"
  echo "    - the '$APP_NETWORK' Docker network, if absent"
  echo "    - compose.yml, start, infra.sh, backup.sh from infra/prod-server/"
  echo "    - .env with freshly generated JWT_SIGNING_KEY, BOOTSTRAP_ADMIN_PASSWORD, ENQUIRY_IP_SALT,"
  echo "      pinned to REGISTRY=$REGISTRY (the '$CHANNEL' channel) and TAG=$TAG"
  $WITH_NGINX && echo "    - /etc/nginx/sites-available/$NGINX_CONF for $PUBLIC_HOST (after the stack is healthy)"
  $WITH_TLS   && echo "    - a Let's Encrypt certificate for $PUBLIC_HOST (after nginx)"
  echo "  It will NOT touch any other app on this server."
  confirm "Proceed with bootstrap?"

  remote "mkdir -p $REMOTE_DIR/backups"
  ok "created $REMOTE_DIR/ and backups/"

  # compose.yml declares both networks `external: true`, so compose will not create them itself -
  # it just fails with a bare "network not found" if either is missing.
  if remote "docker network inspect $APP_NETWORK >/dev/null 2>&1"; then
    ok "docker network '$APP_NETWORK' already exists"
  else
    remote "docker network create $APP_NETWORK >/dev/null"
    ok "created docker network '$APP_NETWORK'"
  fi

  # 'monitoring' belongs to the server's shared observability stack (~/webroot/00-admin/monitoring),
  # not to this app. Creating our own empty one here would let compose start while the OTel agent
  # quietly fails to reach a collector and Prometheus never finds the scrape target.
  if remote "docker network inspect monitoring >/dev/null 2>&1"; then
    ok "docker network 'monitoring' exists (OTel export and scraping will work)"
  else
    note_warning "docker network 'monitoring' does not exist on this server"
    echo "      compose.yml attaches the api to it. Either start the shared monitoring stack"
    echo "      first, or drop the 'monitoring' network from compose.yml for this host."
    echo "      Continuing will fail at 'docker compose up'."
    confirm "Continue anyway?"
  fi

  scp -q infra/prod-server/compose.yml infra/prod-server/start \
         infra/prod-server/infra.sh infra/prod-server/backup.sh "$SSH_HOST:$REMOTE_DIR/"
  remote "chmod +x $REMOTE_DIR/start $REMOTE_DIR/infra.sh $REMOTE_DIR/backup.sh"
  ok "shipped compose.yml, start, infra.sh, backup.sh"

  # The secrets are generated ON THE SERVER, never here. The outer heredoc delimiter is quoted
  # ('REMOTE_SCRIPT') so nothing in it expands locally — the whole block is shipped verbatim over
  # ssh's stdin and run there, so `openssl rand` executes remotely and no secret ever exists on the
  # deploying machine, in its shell history, or on the wire. Only the non-secret values are
  # interpolated locally, as environment assignments; those are visible in the server's process
  # list, which is exactly why no secret is passed that way.
  #
  # JWT_SIGNING_KEY: HS512 needs >= 64 bytes of key material, hence rand 64 (not 48).
  # ENQUIRY_IP_SALT: salts the hash of visitor IPs so stored hashes cannot be reversed.
  # BOOTSTRAP_ADMIN_PASSWORD: usable exactly once - the account is created with
  #   mustChangePassword=true and every other endpoint refuses that token until it is rotated.
  # shellcheck disable=SC2087  # the inner heredoc is meant to expand remotely; that is the point
  ssh "$SSH_HOST" \
    "ENV_PATH=$REMOTE_DIR/.env \
     REGISTRY='$REGISTRY' TAG='$TAG' FRONTEND_PORT='$FRONTEND_PORT' \
     ALLOWED='$PUBLIC_HOST' STAMP='$(date -u +%Y-%m-%dT%H:%M:%SZ)' \
     bash -s" <<'REMOTE_SCRIPT'
set -euo pipefail
umask 077
cat > "$ENV_PATH" <<ENVEOF
# Generated by deploy.sh --bootstrap on $STAMP.
# The secrets below were generated on this server with 'openssl rand' and have never left it.
# Keep this file mode 600.
REGISTRY=$REGISTRY
TAG=$TAG
FRONTEND_PORT=$FRONTEND_PORT

# Rotating this invalidates every issued access and refresh token, logging all staff out.
# That is the correct response to a suspected leak.
JWT_SIGNING_KEY=$(openssl rand -base64 64 | tr -d '\n')

# Single-use: rotate at first CMS login (the app forces it). See GO-LIVE-CHECKLIST.md.
BOOTSTRAP_ADMIN_PASSWORD=$(openssl rand -base64 24)

# Changing this resets every enquiry rate-limit counter.
ENQUIRY_IP_SALT=$(openssl rand -base64 32)

# Angular's SSR engine rejects any Host not listed here. Must match what nginx forwards.
ALLOWED_HOSTS=$ALLOWED
ENVEOF
chmod 600 "$ENV_PATH"
REMOTE_SCRIPT
  ok "wrote .env (mode 600); secrets generated on the server and never transmitted"

  PREVIOUS_TAG=""        # nothing was deployed before; keeps the summary's rollback hint honest
  PREVIOUS_REGISTRY=""
fi

# --- 2. Obtain the images ----------------------------------------------------------------------
# local:  build them here and push. github: they already exist - prove the server can pull them.

if ! $SKIP_BUILD; then
  step "Building and pushing images (delegating to ./build.sh)"
  TAG="$TAG" REGISTRY="$REGISTRY" ./build.sh
  ok "pushed $REGISTRY/abofonsa-{api,web}:$TAG"
elif [[ "$CHANNEL" == "github" ]]; then
  : # nothing to build, and preflight already proved the GitHub-built images are pullable
else
  $VERIFY_ONLY || step "Skipping build (--skip-build); expecting $TAG to already be in $REGISTRY"
fi

# --- 3. Sync compose.yml -----------------------------------------------------------------------
# infra/prod-server/ is the source of truth and the server's copies are downstream of it. Drift
# here is silent and expensive.

if ! $VERIFY_ONLY && ! $BOOTSTRAP && ! $RECOVER; then
  step "Checking the server's compose.yml against infra/prod-server/compose.yml"

  if in_dir "cat compose.yml" | diff -q - infra/prod-server/compose.yml >/dev/null 2>&1; then
    ok "server compose.yml already matches the repo"
  else
    echo "  The server's copy differs (left: server, right: repo):"
    echo ""
    in_dir "cat compose.yml" | diff -u --label "server:compose.yml" --label "repo:compose.yml" \
      - infra/prod-server/compose.yml | sed 's/^/    /' || true
    echo ""
    confirm "Overwrite the server's compose.yml with the repo version?"

    in_dir "cp compose.yml compose.yml.bak-\$(date +%Y%m%d-%H%M%S)"
    scp -q infra/prod-server/compose.yml "$SSH_HOST:$REMOTE_DIR/compose.yml"
    ok "compose.yml synced (previous version kept as compose.yml.bak-*)"
  fi

  # The helper scripts drift too, and backup.sh silently producing an incomplete archive is worse
  # than compose.yml drifting, because nothing fails until a restore is attempted.
  for f in start infra.sh backup.sh; do
    if ! in_dir "cat $f" | diff -q - "infra/prod-server/$f" >/dev/null 2>&1; then
      note_warning "$f differs from the repo copy - shipping the repo version"
      scp -q "infra/prod-server/$f" "$SSH_HOST:$REMOTE_DIR/$f"
      remote "chmod +x $REMOTE_DIR/$f"
    fi
  done
fi

# --- 4. Check the server's .env for required keys ----------------------------------------------
# Reads key names only - values stay on the server and are never printed or copied here.

if ! $VERIFY_ONLY && ! $RECOVER; then
  step "Checking the server's .env"

  REMOTE_ENV_KEYS="$(in_dir "grep -oE '^[A-Z_]+' .env" | sort)"

  # compose.yml marks these `:?` - a missing one aborts `docker compose up` with an error that
  # doesn't obviously point at .env, so catch it here where the message can be specific.
  for key in JWT_SIGNING_KEY BOOTSTRAP_ADMIN_PASSWORD ENQUIRY_IP_SALT; do
    grep -qx "$key" <<<"$REMOTE_ENV_KEYS" || die "$REMOTE_DIR/.env is missing required key $key
        (compose.yml declares it \`:?\`, so the stack will refuse to start)."
  done
  ok "all required keys present"

  # HS512 refuses a key shorter than 64 bytes at startup, and the failure surfaces as a bean
  # creation error rather than anything mentioning .env.
  #
  # Strips the key name with sub() rather than splitting on '=': base64 values end in '=' padding,
  # so -F= would measure only up to the first one and report a legitimate 64-character key as 63.
  if ! in_dir "awk '/^JWT_SIGNING_KEY=/{sub(/^JWT_SIGNING_KEY=/,\"\"); if (length(\$0) >= 64) f=1} END{exit !f}' .env"; then
    die "JWT_SIGNING_KEY in $REMOTE_DIR/.env is shorter than 64 characters.
        HS512 needs at least 64 bytes of key material: openssl rand -base64 64"
  fi
  ok "JWT_SIGNING_KEY is long enough for HS512"

  # ALLOWED_HOSTS is not `:?` (it has a default), but a mismatch makes every page 400 with
  # "Header host ... is not allowed" - a failure that looks like a broken build.
  if in_dir "grep -qE '^ALLOWED_HOSTS=.+' .env"; then
    if ! in_dir "grep -E '^ALLOWED_HOSTS=' .env | grep -q '$PUBLIC_HOST'"; then
      note_warning "ALLOWED_HOSTS on the server does not mention $PUBLIC_HOST - SSR will reject every request with 400"
    else
      ok "ALLOWED_HOSTS includes $PUBLIC_HOST"
    fi
  else
    note_warning "ALLOWED_HOSTS not set on the server - falling back to compose.yml's default"
  fi
fi

# --- 5. Point the server at the new image ------------------------------------------------------
# REGISTRY and TAG together are the image reference, and both are written. Writing only TAG - which
# is all this did while there was one registry - is what breaks the moment a second one exists: the
# tag moves to a SHA that only GHCR has while REGISTRY still says docker.jojoaddison.net, and the
# pull fails on an image that was built perfectly well.

if $BOOTSTRAP; then
  : # bootstrap already wrote REGISTRY and TAG into the .env it generated; re-sed'ing them would
    # only leave a backup file holding a second copy of the freshly generated secrets.
elif ! $VERIFY_ONLY && ! $RECOVER; then
  step "Pointing the server's .env at $REGISTRY/abofonsa-*:$TAG"

  if [[ "$PREVIOUS_TAG" == "$TAG" && "$PREVIOUS_REGISTRY" == "$REGISTRY" ]]; then
    ok "already set (recreate below will still pull a moved tag like :latest)"
  else
    in_dir "cp .env .env.bak-\$(date +%Y%m%d-%H%M%S)"
    set_env_key REGISTRY "$REGISTRY"
    set_env_key TAG "$TAG"
    in_dir "chmod 600 .env .env.bak-*"
    [[ "$PREVIOUS_REGISTRY" == "$REGISTRY" ]] \
      || ok "REGISTRY: ${PREVIOUS_REGISTRY:-<unset>} -> $REGISTRY"
    [[ "$PREVIOUS_TAG" == "$TAG" ]] \
      || ok "TAG: ${PREVIOUS_TAG:-<unset>} -> $TAG"
    ok "previous .env kept as .env.bak-*"
  fi
fi

# --- 6. Pull and restart -----------------------------------------------------------------------

if ! $VERIFY_ONLY && ! $RECOVER; then
  step "Pulling images and recreating the stack"
  if $BOOTSTRAP; then
    echo "  First start: pulls MongoDB and the app images, initialises the replica set, and seeds"
    echo "  the database. Nothing is live yet, so there is no traffic to interrupt."
  else
    echo "  This restarts the live site. MongoDB and the media volume are kept; no data is dropped."
  fi
  confirm "Proceed with pull + up -d on $SSH_HOST?"

  in_dir "docker compose --env-file .env -f compose.yml pull"
  ok "images pulled"

  # --remove-orphans is safe only because compose.yml pins `name: hc-abofonsa`.
  in_dir "docker compose --env-file .env -f compose.yml up -d --remove-orphans"
  ok "containers recreated"
fi

# --- 7. Wait for the API to become healthy -----------------------------------------------------

step "Waiting for $API_CONTAINER to report healthy (up to $((HEALTH_TIMEOUT_SECS / 60)) min)"
echo "  The OTel javaagent makes this slow on purpose - minutes, not seconds, is normal."

deadline=$(( SECONDS + HEALTH_TIMEOUT_SECS ))
last_status=""
while true; do
  status="$(remote "docker inspect $API_CONTAINER --format '{{.State.Health.Status}}' 2>/dev/null" || echo "missing")"

  if [[ "$status" != "$last_status" ]]; then
    echo "  [$(date +%H:%M:%S)] status: $status"
    last_status="$status"
  fi

  case "$status" in
    healthy) ok "API healthy"; break ;;
    unhealthy)
      fail "API reports unhealthy. Last 60 log lines:"
      remote "docker logs --tail 60 $API_CONTAINER" 2>&1 | sed 's/^/    /'
      die "api unhealthy after deploy. Roll back with: $(rollback_hint)"
      ;;
    missing)
      die "$API_CONTAINER does not exist - did 'up -d' fail? Check: ssh $SSH_HOST 'cd $REMOTE_DIR && docker compose ps -a'"
      ;;
  esac

  if (( SECONDS >= deadline )); then
    fail "still '$status' after $((HEALTH_TIMEOUT_SECS / 60)) minutes. Last 60 log lines:"
    remote "docker logs --tail 60 $API_CONTAINER" 2>&1 | sed 's/^/    /'
    die "timed out waiting for health. Re-run with --verify-only to keep checking without redeploying."
  fi

  sleep "$HEALTH_POLL_SECS"
done

# --- 8. Verify on the server -------------------------------------------------------------------

step "Container status"
in_dir "docker compose --env-file .env -f compose.yml ps" | sed 's/^/  /'

remote "docker inspect $WEB_CONTAINER --format '{{.State.Status}}'" | grep -qx running \
  && ok "$WEB_CONTAINER running" \
  || die "$WEB_CONTAINER is not running"

# Publishing content uses multi-document transactions, which MongoDB only offers on a replica set.
# If rs.initiate() never ran, reads work and every publish fails - so check it explicitly.
RS_STATE="$(remote "docker exec $MONGO_CONTAINER mongosh --quiet --eval 'rs.status().myState' 2>/dev/null" || echo "?")"
if [[ "$RS_STATE" == "1" ]]; then
  ok "MongoDB replica set is PRIMARY (transactions available)"
else
  fail "MongoDB replica set state is '$RS_STATE', expected 1 (PRIMARY)."
  die "publishing content will fail without a replica set. Check: docker logs hc_abofonsa_mongo_init"
fi

# Confirms the container came up on the image just deployed, rather than an older one left running
# because a pull silently failed. The whole reference is compared, not just the tag: with two
# channels the registry is now part of the answer to "is this the image I meant", and the same tag
# can exist in both places.
RUNNING_IMAGE="$(remote "docker inspect $API_CONTAINER --format '{{.Config.Image}}'")"
EXPECTED_IMAGE="$REGISTRY/abofonsa-api:$TAG"
echo "  api image: $RUNNING_IMAGE"
[[ "$RUNNING_IMAGE" == "$EXPECTED_IMAGE" ]] \
  && ok "running the expected image ($EXPECTED_IMAGE)" \
  || note_warning "running image is $RUNNING_IMAGE, expected $EXPECTED_IMAGE"

step "Internal checks (on the server, bypassing nginx and TLS)"
# Split from the public checks deliberately: if these pass but the public ones fail, the problem is
# nginx/TLS/DNS, not the app.
#
# The Host header is not optional here. Angular's SSR engine rejects any Host outside ALLOWED_HOSTS
# (its SSRF defence), so a bare `curl 127.0.0.1:8082/` sends `Host: 127.0.0.1:8082` and gets a flat
# 400 from a perfectly healthy container. nginx sets `Host: $http_host` when it proxies, so these
# checks send the same thing — otherwise they test the allowlist rather than the application, and
# report a broken deployment when nothing is wrong.
check_internal() {
  local path="$1" desc="$2"
  local code
  code="$(remote "curl -s -o /dev/null -w '%{http_code}' --max-time 20 -H 'Host: $PUBLIC_HOST' http://127.0.0.1:$FRONTEND_PORT$path" || echo "000")"
  if [[ "$code" == "200" ]]; then ok "$desc -> 200"; else fail "$desc -> $code"; return 1; fi
}
check_internal "/"                              "home page (SSR)"
check_internal "/api/v1/health"                 "API health (proxied through the web container)"
check_internal "/api/v1/content/site?locale=en" "published content payload"

# --- 8b. Bootstrap: host nginx site and TLS ----------------------------------------------------
# Runbook step 4, deliberately after the internal checks: pointing nginx at a stack that isn't
# serving yet just produces a 502 and a confusing certbot failure.

if $BOOTSTRAP && $WITH_NGINX; then
  step "Installing the host nginx site for $PUBLIC_HOST"

  if remote "test -e /etc/nginx/sites-available/$NGINX_CONF"; then
    ok "$NGINX_CONF already exists on the server - leaving it alone"
    warn "if it needs updating, edit infra/prod-server/$NGINX_CONF and copy it up by hand"
  else
    echo "  Writes /etc/nginx/sites-available/$NGINX_CONF (HTTP-only bootstrap version),"
    echo "  symlinks it into sites-enabled, tests the config, and reloads nginx."
    echo "  Other apps' sites on this host are untouched; a failed 'nginx -t' aborts before reload."
    confirm "Install the nginx site for $PUBLIC_HOST?"

    scp -q "infra/prod-server/$NGINX_CONF" "$SSH_HOST:/tmp/$NGINX_CONF"
    remote "sudo mv /tmp/$NGINX_CONF /etc/nginx/sites-available/$NGINX_CONF \
            && sudo ln -sf /etc/nginx/sites-available/$NGINX_CONF /etc/nginx/sites-enabled/$NGINX_CONF"
    ok "site config installed and enabled"

    # nginx -t before reload: a broken config would otherwise take down every site on this host,
    # not just this one.
    if remote "sudo nginx -t" 2>&1 | sed 's/^/    /'; then
      remote "sudo systemctl reload nginx"
      ok "nginx config valid, reloaded"
    else
      remote "sudo rm -f /etc/nginx/sites-enabled/$NGINX_CONF"
      die "nginx -t failed; removed the symlink and did NOT reload. Other sites are unaffected."
    fi
  fi

  if $WITH_TLS; then
    step "Obtaining a TLS certificate for $PUBLIC_HOST"

    if remote "test -d /etc/letsencrypt/live/$PUBLIC_HOST"; then
      ok "certificate for $PUBLIC_HOST already exists - skipping certbot"
    else
      echo "  Runs: certbot --nginx -d $PUBLIC_HOST"
      echo "  This rewrites the site config in place with an SSL block + HTTP->HTTPS redirect."
      echo ""
      echo "  ${BOLD}Before you say yes:${RESET}"
      echo "    - $PUBLIC_HOST must already resolve to this server, or the challenge fails."
      echo "    - Let's Encrypt rate-limits duplicate certs (5/week per domain), and issuance"
      echo "      publishes the hostname to public Certificate Transparency logs. A wrong answer"
      echo "      here is not freely retryable and not quietly undoable."
      # Deliberately prompts even under --yes: this is an outward-facing, rate-limited, effectively
      # irreversible action against a real certificate authority and a real public log.
      read -r -p "  ${BOLD}Run certbot for $PUBLIC_HOST now?${RESET} [y/N] " reply
      if [[ "$reply" =~ ^[Yy]$ ]]; then
        remote "sudo certbot --nginx -d $PUBLIC_HOST --non-interactive --agree-tos --register-unsafely-without-email --redirect" \
          && ok "certificate issued and nginx reconfigured for HTTPS" \
          || die "certbot failed. The HTTP-only site is still serving; fix DNS and re-run certbot by hand."
      else
        note_warning "skipped certbot - $PUBLIC_URL will not work until a certificate exists"
      fi
    fi
  fi
fi

# --- 9. Public verification --------------------------------------------------------------------

if $BOOTSTRAP && ! remote "test -d /etc/letsencrypt/live/$PUBLIC_HOST" 2>/dev/null; then
  step "Public checks - skipped"
  note_warning "no TLS certificate on the server yet, so $PUBLIC_URL cannot be checked"
  echo "      Finish by pointing DNS at this server and re-running with --with-nginx --with-tls,"
  echo "      or by running certbot on the server yourself. Then: ./deploy.sh --verify-only"
  SKIP_PUBLIC=true
else
  SKIP_PUBLIC=false
fi

check_public() {
  local path="$1" desc="$2" expect="${3:-200}"
  local code
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 25 "$PUBLIC_URL$path" || echo "000")"
  if [[ "$code" == "$expect" ]]; then ok "$desc -> $code"; else fail "$desc -> $code (expected $expect)"; return 1; fi
}

PUBLIC_OK=true
if ! $SKIP_PUBLIC; then
  step "Public checks ($PUBLIC_URL)"

  check_public "/"                              "home page"          || PUBLIC_OK=false
  check_public "/api/v1/health"                 "GET /api/v1/health" || PUBLIC_OK=false
  check_public "/api/v1/content/site?locale=en" "content payload"    || PUBLIC_OK=false

  # Each locale is an independently routed, server-rendered page (spec §5.4). A wrong `lang` means
  # SSR silently fell back to English, which no status code would reveal.
  #
  # The body is captured first rather than piped into grep. Under `set -o pipefail`, `curl | grep -q`
  # is actively wrong: grep exits the instant it matches, curl is left writing into a closed pipe and
  # fails with exit 23, and pipefail reports the *successful* match as a failed pipeline. It only
  # shows up on responses big enough that curl is still writing — which is why the tiny header checks
  # below always passed while this 240 kB page always "failed".
  for locale in en es fr de; do
    path=$([[ "$locale" == "en" ]] && echo "/" || echo "/$locale")
    page_html="$(curl -s --max-time 25 "$PUBLIC_URL$path" || true)"
    if grep -q "<html lang=\"$locale\"" <<<"$page_html"; then
      ok "$path renders lang=\"$locale\""
    else
      fail "$path did not render lang=\"$locale\" - SSR locale resolution is broken"
      PUBLIC_OK=false
    fi
  done

  # Publishing must be visible immediately, so the HTML must never be served stale from a cache.
  CACHE_HEADER="$(grep -i '^cache-control:' <<<"$(curl -sI --max-time 20 "$PUBLIC_URL/" || true)" | tr -d '\r' || true)"
  if grep -qi 'no-cache' <<<"$CACHE_HEADER"; then
    ok "HTML revalidates (${CACHE_HEADER:-none})"
  else
    note_warning "home page Cache-Control is '${CACHE_HEADER:-<absent>}', expected no-cache - published edits may appear stale"
  fi

  # Every response should carry a correlation id; support quotes it when reporting a problem.
  if grep -qi '^x-request-id:' <<<"$(curl -sI --max-time 20 "$PUBLIC_URL/api/v1/health" || true)"; then
    ok "responses carry X-Request-Id"
  else
    note_warning "no X-Request-Id header - correlation ids are not reaching clients"
  fi

  # Indexability is reported, never asserted: both answers are legitimate, and which one is correct
  # depends on whether this deployment is the announced site or a review of it. Getting it wrong is
  # silent and slow to undo in one direction, so it is stated plainly on every deploy.
  ROBOTS_TXT="$(curl -s --max-time 20 "$PUBLIC_URL/robots.txt" || true)"
  ROBOTS_META="$(grep -o '<meta name="robots"[^>]*>' <<<"$(curl -s --max-time 25 "$PUBLIC_URL/" || true)" | head -1 || true)"
  if grep -q 'Disallow: /$' <<<"$ROBOTS_TXT"; then
    ok "search engines are excluded (robots.txt disallows all)"
    grep -q 'noindex' <<<"$ROBOTS_META" \
      || note_warning "robots.txt disallows all but the page meta says '${ROBOTS_META:-<absent>}' - these disagree"
    echo "      To make this deployment indexable: set SITE_INDEXABLE=true in $REMOTE_DIR/.env and redeploy."
  else
    ok "search engines are allowed (robots.txt: ${ROBOTS_TXT//$'\n'/ })"
    grep -q 'noindex' <<<"$ROBOTS_META" \
      && note_warning "robots.txt allows crawling but the page still says noindex - these disagree"
    warn "this deployment is indexable - correct only if $PUBLIC_HOST is the announced public site"
  fi

  # The CMS must never be indexable, and must not be server-rendered into a login redirect.
  check_public "/admin/login" "CMS login page" || note_warning "CMS login page not reachable"

  # Certbot renews on a cron, so this is early warning, not a deploy gate.
  CERT_END="$(echo | openssl s_client -connect "$PUBLIC_HOST:443" -servername "$PUBLIC_HOST" 2>/dev/null \
    | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2 || true)"
  if [[ -n "$CERT_END" ]]; then
    CERT_DAYS=$(( ( $(date -d "$CERT_END" +%s) - $(date +%s) ) / 86400 ))
    if (( CERT_DAYS < 14 )); then
      note_warning "TLS certificate expires in $CERT_DAYS days ($CERT_END) - check certbot's renewal timer"
    else
      ok "TLS certificate valid for $CERT_DAYS more days"
    fi
  fi
fi

$PUBLIC_OK || die "public verification failed - the app is not correctly serving at $PUBLIC_URL"

# --- 10. Summary -------------------------------------------------------------------------------

if $VERIFY_ONLY; then
  step "Verification summary"
  echo "  image running: ${BOLD}$REGISTRY/abofonsa-*:$TAG${RESET}"
elif $BOOTSTRAP; then
  step "Bootstrap summary"
  echo "  installed at:  $SSH_HOST:$REMOTE_DIR"
  echo "  channel:       ${BOLD}$CHANNEL${RESET} ($REGISTRY)"
  echo "  tag deployed:  ${BOLD}$TAG${RESET}"
else
  step "Deployment summary"
  CHANNEL_NOTE=""
  [[ -n "$PREVIOUS_REGISTRY" && "$PREVIOUS_REGISTRY" != "$REGISTRY" ]] && CHANNEL_NOTE="  (previously: $PREVIOUS_REGISTRY)"
  echo "  channel:       ${BOLD}$CHANNEL${RESET} ($REGISTRY)$CHANNEL_NOTE"
  echo "  tag deployed:  ${BOLD}$TAG${RESET}${PREVIOUS_TAG:+  (previous: $PREVIOUS_TAG)}"
fi
echo "  live at:       $PUBLIC_URL"
$VERIFY_ONLY || echo "  roll back:     $(rollback_hint)"
echo "  logs:          ssh $SSH_HOST 'docker logs -f $API_CONTAINER'"
echo "  re-verify:     ./deploy.sh --verify-only"

if $BOOTSTRAP; then
  echo ""
  echo "  ${BOLD}Still to do by hand${RESET} (this script deliberately does not):"
  echo "    - ${BOLD}Rotate the bootstrap admin password.${RESET} Read it from the server:"
  echo "        ssh $SSH_HOST 'grep BOOTSTRAP_ADMIN_PASSWORD $REMOTE_DIR/.env'"
  echo "      then sign in at $PUBLIC_URL/admin - the CMS forces a change on first login."
  echo "    - Nightly backups: add to root's crontab on $SSH_HOST:"
  echo "        0 2 * * * $REMOTE_DIR/backup.sh"
  echo "      then run it once by hand and restore it into a scratch stack. A backup that has"
  echo "      never been restored is not a backup - see infra/PRODUCTION_DEPLOYMENT_PLAN.md."
  echo "    - Load infra/observability/ into the shared Prometheus (alert rules + uptime targets)."
  echo "    - Work through GO-LIVE-CHECKLIST.md before announcing the site."
fi

if (( ${#WARNINGS[@]} > 0 )); then
  echo ""
  echo "  ${YELLOW}${BOLD}${#WARNINGS[@]} warning(s):${RESET}"
  for w in "${WARNINGS[@]}"; do echo "    ${YELLOW}!${RESET} $w"; done
fi

echo ""
if $VERIFY_ONLY; then
  echo "${GREEN}${BOLD}Production is up and serving correctly.${RESET}"
elif $BOOTSTRAP && $SKIP_PUBLIC; then
  echo "${GREEN}${BOLD}Bootstrap complete.${RESET} The stack is healthy and serving on the server;"
  echo "finish the DNS/TLS steps above to make it reachable at $PUBLIC_URL."
elif $BOOTSTRAP; then
  echo "${GREEN}${BOLD}Bootstrap complete and verified.${RESET} The site is live at $PUBLIC_URL."
else
  echo "${GREEN}${BOLD}Deploy complete and verified.${RESET}"
fi
